### ISSUE TITLE
Western Frysian is not a language

### ISSUE THREAD

**Issue by paddotk** [cospired/i18n-iso-languages#12]
Frysian is.

**Comment by e110c0** [comment]
The official ISO 639 name is `Western Frisian` according to this list https://www.loc.gov/standards/iso639-2/php/English_list.php

if I look at wikipedia https://en.wikipedia.org/wiki/West_Frisian_language, it says:

```The name "West Frisian" is only used outside the Netherlands, to distinguish this language from the closely related Frisian languages```

since it is an international standard and the name should be understood everywhere, it makes sense to use the long name. If in Dutch there is a different name for it, the Dutch translation should reflect that.

**Comment by paddotk** [comment]
Ah I understand. Too bad that Wikipedia is so often used as a source (I understand for your sake, though), unfortunely this is not valid information. I'm Dutch myself, there is a language 'Frisian' but no such thing as 'West Frisian', this is a regional accent at best, if worth naming at all. This is not a matter of what it's called in Dutch vs English ;)

I understand if you can't take my word for it though.

**Comment by e110c0** [comment]
actually, the main source I quoted is the ISO639-2 standard. There it is called `Western Frisian`. The wikipedia is only used as possible explanation for the different usage in English and Dutch. 

It makes a difference, as written in the wikipedia article. The Language is called 'Frisian' in Dutch and 'West Frisian' is an accent. In English though, the language is called 'Western Frisian' (not 'West Frisian'!).

This package provides translations for language names. If the name for `fry` is different in English and Dutch, that should be reflected in the Dutch translations. For English, we are using the names provided in the standard
