### ISSUE TITLE
A new language requst: zh-TW

### ISSUE THREAD

**Issue by 12cassie34** [cospired/i18n-iso-languages#53]
Hello language lovers,
(Language here refers to whether(or both) programming languages or natural languages. 🚀)

First of all, thanks for creating and maintaining this great repo. My colleagues and I love it!

I'm wondering if it's possible for me to contribute a new language which its code is '**zh-TW**'(Traditional Chinese).

I know that zh-TW doesn't exist on the list of ISO 639-1, but that's the official language of Republic of China(Taiwan) which means that it's used by more than 24,000,000 people.

People might wonder what's the difference between `zh` and `zh-TW`, is it really necessary to add `zh-TW`.
Well, the two languages are very different from each other, for example

1. The characters are different:
<table>
<tr>
<td>en</td>
<td>zh</td>
<td>zh-TW</td>
</tr>
<tr>
<td>Finnish</td>
<td>芬兰语</td>
<td>芬蘭語</td>
</tr>
<tr>
<td>Malay</td>
<td>马来语</td>
<td>馬來語</td>
</tr>
</table>

2. The translations of languages between `zh` and `zh-TW` may be different, when it comes to:
- Azerbaijani: we say "`亞`塞拜`然`語" instead of "`阿`塞拜`疆`语".
- Lao: we say "`高棉`語" instead of "`老挝`语".
- Kinyarwanda: we say "盧`安`達語" instead of "卢`旺`达语".
- Venda: we say "`溫`達語" instead of "`文`达语".
... etc

I'm ready to contribute but instead of pulling a request, I think it's better to have a conversation to discuss about this beforehand. Since it's an  open source repo 🙂.

Thanks for reading!

**Comment by e110c0** [comment]
While I understand the reasoning behind this, the idea of this library is to provide ISO 639 language code translations.
For one thing, `zh-TW` is a [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag), and as you mentioned, is not reflected in ISO 639. 

I don't see how this can be done in a consistent way for this library, because there is no 2 letter or (for ISO 639-2/3) 3 letter code for this language.

so this either means breaking completely with ISO 639, nor adding full IETF language tag support, with the side effect that not all languages will be represented in both IETF and ISO-639.

I think this is out of scope of this library at this moment

**Comment by 12cassie34** [comment]
Hello
Got it! Yes, I can totally understand the idea of this library.
Thanks for replying me anyway🙂.
